CREATE ROLE thinc_migrator
  LOGIN PASSWORD 'change-me-migration'
  NOSUPERUSER NOCREATEDB NOCREATEROLE NOBYPASSRLS;
CREATE ROLE thinc_app
  LOGIN PASSWORD 'change-me-app'
  NOSUPERUSER NOCREATEDB NOCREATEROLE NOBYPASSRLS;
CREATE DATABASE thinc OWNER thinc_migrator;
CREATE DATABASE thinc_test OWNER thinc_migrator;
